# Generated by Django 5.0.7 on 2024-08-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
