# Generated by Django 5.0.7 on 2024-08-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_seller_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('product_category', models.IntegerField(blank=True, choices=[(1, 'shoe'), (2, 'cloth')], null=True)),
                ('type_of_category', models.IntegerField(blank=True, choices=[(1, 'men'), (2, 'women'), (3, 'unisex')], null=True)),
                ('sellers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seller')),
            ],
        ),
    ]
