# Generated by Django 5.0.7 on 2024-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_type_of_category_product_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
