# Generated by Django 5.0.7 on 2024-08-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_price_product_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
