# Generated by Django 5.0.7 on 2024-08-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.IntegerField(blank=True, choices=[(1, 'shoe'), (2, 'cloth'), (3, 'accessories')], null=True),
        ),
    ]
