# Generated by Django 5.0.7 on 2024-08-31 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_add_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiration', models.CharField(max_length=7)),
                ('card_cvv', models.CharField(max_length=7)),
                ('add_to_cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.add_to_cart')),
            ],
        ),
    ]
