# Generated by Django 5.0.7 on 2024-08-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_payment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
