# Generated by Django 5.0.7 on 2024-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_product',
            name='order_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_product',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_product',
            name='product_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
