# Generated by Django 5.0.7 on 2024-09-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='product_feedback',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
            preserve_default=False,
        ),
    ]
